import React, { useState, useEffect } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";

const DateComponent = () => {
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [verifiedUsers, setVerifiedUsers] = useState([]);
  const [users, setUsers] = useState([]); // State to store users list

  // Fetch the verified users from the backend
  useEffect(() => {
    const fetchVerifiedUsers = async () => {
      try {
        const response = await axios.get(
          "http://localhost:5000/api/adhar/verified"
        );
        setVerifiedUsers(response.data); // Set the fetched data into the state
      } catch (error) {
        console.error("Error fetching verified users:", error);
      }
    };
    fetchVerifiedUsers();
  },[]);


  

  const handleDelete = async (aadharNumber) => {
    // Show confirmation dialog
    const isConfirmed = window.confirm("Are you sure you want to delete this user?");
  
    // If user clicks "Yes"
    if (isConfirmed) {
      try {
        const response = await axios.delete(`http://localhost:5000/api/adhar/delete/${aadharNumber}`);
        
        if (response.data.message === "User deleted successfully.") {
          // If deletion is successful, update state by filtering out the deleted user
          setUsers((prevUsers) => prevUsers.filter((user) => user.aadharNumber !== aadharNumber));
          alert("User deleted successfully.");
        } else {
          alert("Failed to delete user.");
        }
      } catch (error) {
        console.error("Error deleting user:", error);
        alert("Failed to delete user. Please try again.");
      }
    } else {
      // If user clicks "No", just return without deleting
      alert("User deletion canceled.");
    }
  };
  

  // Function to generate and download the PDF
//   const handleDownloadPdf = (user) => {
//     const doc = new jsPDF();

//     // Add title
//     doc.setFont("helvetica", "bold");
//     doc.setFontSize(16);
//     doc.text("Aadhaar Verification Details", 14, 20);

//     doc.setLineWidth(0.5);
//     doc.line(10, 22, 200, 22);

//     // Add Aadhaar details
//     doc.setFont("helvetica", "normal");
//     doc.setFontSize(12);
//     doc.text(`Aadhaar Number: ${user.aadharNumber}`, 14, 75);
//     doc.text(`Name: ${user.verifiedData?.data?.full_name}`, 14, 85);
//     doc.text(`Gender: ${user.verifiedData?.data?.gender}`, 14, 95);
//     doc.text(`DOB: ${user.verifiedData?.data?.dob}`, 14, 105);

//     doc.text("Address:", 14, 115);
//     const addressLines = [
//       user?.verifiedData?.data?.address?.house,
//       user?.verifiedData?.data?.address?.street,
//       user?.verifiedData?.data?.address?.landmark,
//       user?.verifiedData?.data?.address?.loc,
//       user?.verifiedData?.data?.address?.po,
//       user?.verifiedData?.data?.address?.subdist,
//       user?.verifiedData?.data?.address?.dist,
//       user?.verifiedData?.data?.address?.state,
//       user?.verifiedData?.data?.address?.country,
//       user?.verifiedData?.data?.address?.zip,
//     ]
//       .filter(Boolean)
//       .join(", ");
//     const addressSplit = doc.splitTextToSize(addressLines, 180);
//     doc.text(addressSplit, 14, 120);

//     // Add the profile image
//     const imageData = `data:image/jpeg;base64,${user.verifiedData.data.profile_image}`;

//     // Add the image to the PDF (positioned at x=14, y=30 with width=50 and height=50)
//     doc.addImage(imageData, "JPEG", 14, 30, 35, 35);

//     // Footer text
//     doc.setFont("helvetica", "italic");
//     doc.setFontSize(10);
//     doc.text("Generated by Aadhaar Verification System", 14, 290);

//     // Save the PDF
//     doc.save(`${user.verifiedData?.data?.full_name}_aadhaar_verification.pdf`);
//   };

const handleDownloadPdf = (user) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth(); // Page width
    const pageHeight = doc.internal.pageSize.getHeight(); // Page height
  
    // Add a full-page border
    doc.setDrawColor(0); // Black color
    doc.setLineWidth(0.7); // Border thickness
    doc.rect(5, 5, pageWidth - 10, pageHeight - 10); // Draw rectangle with a 5-unit margin from each edge
  
    // Center-aligned title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(25);
    const title = "Shankar Nagari Sahakari Bank Ltd";
    doc.text(title, (pageWidth - doc.getTextWidth(title)) / 2, 20);
  
    // Center-aligned subtitle
    doc.setFontSize(14);
    const subtitle = "Aadhar Verification Certificate";
    doc.text(subtitle, (pageWidth - doc.getTextWidth(subtitle)) / 2, 28);
  
    // Center-aligned section header
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    const header = "TO WHOMSOEVER IT MAY CONCERN";
    doc.text(header, (pageWidth - doc.getTextWidth(header)) / 2, 36);
  
    // Verification Statement
    const verificationText = `This is to Certify that ${
      user.verifiedData?.data?.full_name || "N/A"
    }, Aadhaar no. ${
      user.aadharNumber ? user.aadharNumber.toString() : "N/A"
    } are verified from https://uidai.gov.in/ using with OTP.`;
    const verificationSplit = doc.splitTextToSize(verificationText, 180);
    doc.text(verificationSplit, 14, 50);
  
    // Define positions and dimensions for the outer border
    const outerX = 10;
    const outerY = 65;
    const outerWidth = 190;
    const outerHeight = 80;
  
    // Draw the outer border
    doc.setDrawColor(0);
    doc.setLineWidth(0.7);
    doc.rect(outerX, outerY, outerWidth, outerHeight);
  
    // Define positions and dimensions for content box
    const contentX = 14;
    const contentY = 70;
    const contentWidth = 120;
    const contentHeight = 90;
  
    // Define positions and dimensions for the profile image box
    const imageX = 150;
    const imageY = 70;
    const imageWidth = 40;
    const imageHeight = 40;
  
    // User Details Content
    doc.setFont("helvetica", "bold");
    doc.text("Name                    :", contentX + 2, contentY + 5);
    doc.setFont("helvetica", "normal");
    doc.text(user.verifiedData?.data?.full_name || "N/A", contentX + 40, contentY + 5);
  
    doc.setFont("helvetica", "bold");
    doc.text("Aadhaar Number :", contentX + 2, contentY + 15);
    doc.setFont("helvetica", "normal");
    doc.text(user.aadharNumber ? user.aadharNumber.toString() : "N/A", contentX + 40, contentY + 15);
  
    doc.setFont("helvetica", "bold");
    doc.text("DOB                      :", contentX + 2, contentY + 25);
    doc.setFont("helvetica", "normal");
    doc.text(user.verifiedData?.data?.dob || "N/A", contentX + 40, contentY + 25);
  
    doc.setFont("helvetica", "bold");
    doc.text("Gender                  : ", contentX + 2, contentY + 35);
    doc.setFont("helvetica", "normal");
    doc.text(user.verifiedData?.data?.gender || "N/A", contentX + 40, contentY + 35);
  
    doc.setFont("helvetica", "bold");
    doc.text("Address                : ", contentX + 2, contentY + 45);
    doc.setFont("helvetica", "normal");
    const addressLines = [
      user?.verifiedData?.data?.address?.house,
      user?.verifiedData?.data?.address?.street,
      user?.verifiedData?.data?.address?.landmark,
      user?.verifiedData?.data?.address?.loc,
      user?.verifiedData?.data?.address?.po,
      user?.verifiedData?.data?.address?.subdist,
      user?.verifiedData?.data?.address?.dist,
      user?.verifiedData?.data?.address?.state,
      user?.verifiedData?.data?.address?.country,
      user?.verifiedData?.data?.zip,
    ]
      .filter(Boolean)
      .join(", ");
    const addressSplit = doc.splitTextToSize(addressLines || "N/A", contentWidth - 50);
    doc.text(addressSplit, contentX + 40, contentY + 45);
  
    // Draw the rectangle for the profile image
    doc.setLineWidth(0.5);
    doc.rect(imageX, imageY, imageWidth, imageHeight);
  
    // Add the profile image or fallback text
    if (user.verifiedData?.data?.profile_image) {
      const imageData = `data:image/jpeg;base64,${user.verifiedData.data.profile_image}`;
      doc.addImage(imageData, "JPEG", imageX, imageY, imageWidth, imageHeight);
    } else {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.text("Profile image not available", imageX + 5, imageY + 20);
    }
  
    // Footer with signatures
    doc.setFont("helvetica", "bold");
    doc.text("Signature of the Authorised Signatory", 14, 170);
    doc.text("Signature of the Branch Manager", 110, 170);
  
    doc.setFont("helvetica", "normal");
    doc.text("Name: __________________", 14, 180);
    doc.text("Name: __________________", 110, 180);
  
    doc.text("Designation: ____________", 14, 190);
    doc.text("Designation: ____________", 110, 190);
  
    doc.text("Phone no.: ______________", 14, 200);
    doc.text("Date: ___________________", 110, 200);
  
    // Bank Seal
    doc.setFont("helvetica", "normal");
    doc.text("(Bank Seal)", 14, 220);
    doc.text("Verified By : User", 120, 220);
  
    // Save PDF
    const fileName = user.verifiedData?.data?.full_name
      ? `${user.verifiedData.data.full_name}_verification_certificate.pdf`
      : "verification_certificate.pdf";
    doc.save(fileName);
  };
  
  

  return (
    <>
      <h3 style={{
                  marginTop:'120px'
                }}>Verified Users</h3>
      <div className="row mb-5">
        <div className="col-md-2">
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            placeholder="Start Date"
          />
        </div>
        <div className="col-md-2 offset-md-8">
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            placeholder="End Date"
          />
        </div>
      </div>

      <div
        style={{
          maxHeight: "400px", // Set the desired maximum height for the table container
          overflowY: "auto", // Enable vertical scrolling
          border: "1px solid #ddd", // Optional: Add a border to the container
        }}
      >
        <table>
          <thead>
            <tr>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Photo
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Aadhaar Number
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Name
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Gender
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                DOB
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Address
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Verification Date
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Action
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Delete
              </th>
            </tr>
          </thead>
          <tbody>
            {verifiedUsers
              .filter((user) => {
                const userVerificationDate = new Date(user.verificationDate);
                let isInDateRange = true;

                // Ensure endDate includes the full last minute of the selected date
                let endDateObj = new Date(endDate);
                if (endDate) {
                  endDateObj.setHours(23, 59, 59, 999); // Set to the last millisecond of the day
                }

                // If startDate equals endDate and is provided, filter for that specific date
                if (startDate === endDate && startDate !== "") {
                  if (
                    userVerificationDate.toDateString() !==
                    new Date(startDate).toDateString()
                  ) {
                    isInDateRange = false;
                  }
                } else {
                  // Check if the user verification date is within the date range
                  isInDateRange =
                    (startDate === "" ||
                      userVerificationDate >= new Date(startDate)) &&
                    (endDate === "" || userVerificationDate <= endDateObj); // Use the modified endDateObj here
                }

                return isInDateRange;
              })
              .map((user, index) => (
                <tr key={index} style={{ border: "1px solid #ddd" }}>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                  <img
                    src={`data:image/jpeg;base64,${user.verifiedData.data.profile_image}`}
                    alt="Aadhaar Profile"
                    style={{ width: "150px", height: "150px", borderRadius: "5%" }}
                    />
                  </td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.aadharNumber}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data?.full_name || "Name not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data?.gender || "Gender not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data?.dob || "DOB not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                    {[user?.verifiedData?.data?.address?.house, user?.verifiedData?.data?.address?.street, user?.verifiedData?.data?.address?.landmark, user?.verifiedData?.data?.address?.loc, user?.verifiedData?.data?.address?.po, user?.verifiedData?.data?.address?.subdist, user?.verifiedData?.data?.address?.dist, user?.verifiedData?.data?.address?.state, user?.verifiedData?.data?.address?.country, user?.verifiedData?.data?.address?.zip]
                    .filter(Boolean)
                    .join(", ") || "No Address Available"}
                </td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                  {user.formattedDate || "DOB not available"}
                  </td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                    <button
                      onClick={() => handleDownloadPdf(user)}
                      title="Download PDF"
                      style={{
                        backgroundColor: "#4CAF50",
                        color: "white",
                        border: "none",
                        padding: "5px 10px",
                        borderRadius: "5px",
                        cursor: "pointer",
                      }}
                    >
                      <box-icon name='download'></box-icon>
                    </button>
                  </td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                    <button
                    onClick={() => handleDelete(user.aadharNumber)}
                    title="Delete"
                    style={{
                        backgroundColor: "#f44336",
                        color: "white",
                        border: "none",
                        padding: "5px 10px",
                        borderRadius: "5px",
                        cursor: "pointer",
                    }}
                    >
                      <box-icon name="trash" type="solid"></box-icon>

                    </button>
                </td>
                </tr>
              ))}
          </tbody>
        </table>
      </div>
      {/* <button
        onClick={() => {
          localStorage.clear(); // Clears all data from localStorage
          alert("All local storage data has been cleared!");
        }}
        style={{
          padding: "10px 20px",
          backgroundColor: "#FF6347", // Color for the button
          color: "white",
          border: "none",
          borderRadius: "5px",
          cursor: "pointer",
        }}
      >
        Clear All Data
      </button> */}
    </>
  );
};

export default DateComponent;
