import React, { useState, useEffect } from "react";
import axios from "axios";
import { jsPDF } from "jspdf";

const VoterTable = () => {
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [verifiedUsers, setVerifiedUsers] = useState([]);
  const [users, setUsers] = useState([]); // State to store users list

  // Fetch the verified users from the backend
  useEffect(() => {
    const fetchVerifiedUsers = async () => {
      try {
        const response = await axios.get(
          "http://localhost:5000/api/voter/verified"
        );
        setVerifiedUsers(response.data); // Set the fetched data into the state
      } catch (error) {
        console.error("Error fetching verified users:", error);
      }
    };
    fetchVerifiedUsers();
  },[]);


  

  const handleDelete = async (aadharNumber) => {
    // Show confirmation dialog
    const isConfirmed = window.confirm("Are you sure you want to delete this user?");
  
    // If user clicks "Yes"
    if (isConfirmed) {
      try {
        const response = await axios.delete(`http://localhost:5000/api/voter/delete/${aadharNumber}`);
        
        if (response.data.message === "User deleted successfully.") {
          // If deletion is successful, update state by filtering out the deleted user
          setUsers((prevUsers) => prevUsers.filter((user) => user.aadharNumber !== aadharNumber));
          alert("User deleted successfully.");
        } else {
          alert("Failed to delete user.");
        }
      } catch (error) {
        console.error("Error deleting user:", error);
        alert("Failed to delete user. Please try again.");
      }
    } else {
      // If user clicks "No", just return without deleting
      alert("User deletion canceled.");
    }
  };
  

  // Function to generate and download the PDF
//   const handleDownloadPdf = (user) => {
//     const doc = new jsPDF();

//     // Add title
//     doc.setFont("helvetica", "bold");
//     doc.setFontSize(16);
//     doc.text("Aadhaar Verification Details", 14, 20);

//     doc.setLineWidth(0.5);
//     doc.line(10, 22, 200, 22);

//     // Add Aadhaar details
//     doc.setFont("helvetica", "normal");
//     doc.setFontSize(12);
//     doc.text(`Aadhaar Number: ${user.aadharNumber}`, 14, 75);
//     doc.text(`Name: ${user.verifiedData?.data?.full_name}`, 14, 85);
//     doc.text(`Gender: ${user.verifiedData?.data?.gender}`, 14, 95);
//     doc.text(`DOB: ${user.verifiedData?.data?.dob}`, 14, 105);

//     doc.text("Address:", 14, 115);
//     const addressLines = [
//       user?.verifiedData?.data?.address?.house,
//       user?.verifiedData?.data?.address?.street,
//       user?.verifiedData?.data?.address?.landmark,
//       user?.verifiedData?.data?.address?.loc,
//       user?.verifiedData?.data?.address?.po,
//       user?.verifiedData?.data?.address?.subdist,
//       user?.verifiedData?.data?.address?.dist,
//       user?.verifiedData?.data?.address?.state,
//       user?.verifiedData?.data?.address?.country,
//       user?.verifiedData?.data?.address?.zip,
//     ]
//       .filter(Boolean)
//       .join(", ");
//     const addressSplit = doc.splitTextToSize(addressLines, 180);
//     doc.text(addressSplit, 14, 120);

//     // Add the profile image
//     const imageData = `data:image/jpeg;base64,${user.verifiedData.data.profile_image}`;

//     // Add the image to the PDF (positioned at x=14, y=30 with width=50 and height=50)
//     doc.addImage(imageData, "JPEG", 14, 30, 35, 35);

//     // Footer text
//     doc.setFont("helvetica", "italic");
//     doc.setFontSize(10);
//     doc.text("Generated by Aadhaar Verification System", 14, 290);

//     // Save the PDF
//     doc.save(`${user.verifiedData?.data?.full_name}_aadhaar_verification.pdf`);
//   };

const handleDownloadPdf = (user) => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth(); // Page width
      const pageHeight = doc.internal.pageSize.getHeight(); // Page height
  
      // Add a full-page border
      doc.setDrawColor(0); // Black color
      doc.setLineWidth(0.7); // Border thickness
      doc.rect(5, 5, pageWidth - 10, pageHeight - 10); // Draw rectangle with a 5-unit margin from each edge
  
      // Center-aligned title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(25);
      const title = "Shankar Nagari Sahakari Bank Ltd";
      doc.text(title, (pageWidth - doc.getTextWidth(title)) / 2, 20);
  
      // Center-aligned subtitle
      doc.setFontSize(14);
      const subtitle = "Voter Id Verification Certificate";
      doc.text(subtitle, (pageWidth - doc.getTextWidth(subtitle)) / 2, 28);
  
      // Center-aligned section header
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      const header = "TO WHOMSOEVER IT MAY CONCERN";
      doc.text(header, (pageWidth - doc.getTextWidth(header)) / 2, 36);
  
      // Verification Statement
      const name = user?.verifiedData?.data?.name || "N/A";
      const idNumber = user?.id_number || "N/A";
      const verificationText = `This is to Certify that ${name}, Voter Id No. ${idNumber} are verified from link.`;
      const verificationSplit = doc.splitTextToSize(verificationText, 180);
      doc.text(verificationSplit, 14, 50);
  
      // User Details Content
      const userDetails = [
        { label: "Status", value: "success" },
        { label: "Id Number", value: idNumber },
        { label: "Name", value: name },
        { label: "Age", value: user?.verifiedData?.data?.age?.toString() || "N/A" },
        { label: "Gender", value: user?.verifiedData?.data?.gender || "N/A" },
        { label: "Relation Name", value: user?.verifiedData?.data?.relation_name || "N/A" },
        { label: "Relation Type", value: user?.verifiedData?.data?.relation_type || "N/A" },
        { label: "State", value: user?.verifiedData?.data?.state || "N/A" },
        { label: "District", value: user?.verifiedData?.data?.district || "N/A" },
        { label: "Polling Station", value: user?.verifiedData?.data?.polling_station || "N/A" },
        { label: "Assembly Constituency", value: user?.verifiedData?.data?.assembly_constituency || "N/A" },
        { label: "Constituency Number", value: user?.verifiedData?.data?.assembly_constituency_number || "N/A" },
        { label: "Part Number", value: user?.verifiedData?.data?.part_number || "N/A" },
        { label: "Part Name", value: user?.verifiedData?.data?.part_name || "N/A" },
        { label: "Parliamentary Name", value: user?.verifiedData?.data?.parliamentary_name || "N/A" },
        { label: "Parliamentary Number", value: user?.verifiedData?.data?.parliamentary_number || "N/A" },
      ];
  
      doc.setFont("helvetica", "bold");
      let yOffset = 70;
  
      userDetails.forEach((item) => {
        doc.text(`${item.label} :`, 14, yOffset);
        doc.setFont("helvetica", "normal");
        doc.text(item.value, 60, yOffset);
        yOffset += 10;
      });
  
      // Save PDF
      const fileName = `${name}_verification_certificate.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error("Error generating PDF:", error);
    }
  };
  
  
  

  return (
    <>
      <h3 style={{
                  marginTop:'120px'
                }}>Verified Users</h3>
      <div className="row mb-5">
        <div className="col-md-2">
          <input
            type="date"
            value={startDate}
            onChange={(e) => setStartDate(e.target.value)}
            placeholder="Start Date"
          />
        </div>
        <div className="col-md-2 offset-md-8">
          <input
            type="date"
            value={endDate}
            onChange={(e) => setEndDate(e.target.value)}
            placeholder="End Date"
          />
        </div>
      </div>

      <div
        style={{
          maxHeight: "400px", // Set the desired maximum height for the table container
          overflowY: "auto", // Enable vertical scrolling
          border: "1px solid #ddd", // Optional: Add a border to the container
        }}
      >
        <table>
          <thead>
            <tr>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Voter ID
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Name
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Age
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Gender
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                District
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                State
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Polling Station
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Verification Date
              </th>
              <th
                style={{
                  padding: "8px",
                  border: "1px solid #ddd",
                  textAlign: "left",
                }}
              >
                Download
              </th>
            </tr>
          </thead>
          <tbody>
            {verifiedUsers
              .filter((user) => {
                const userVerificationDate = new Date(user.verificationDate);
                let isInDateRange = true;

                // Ensure endDate includes the full last minute of the selected date
                let endDateObj = new Date(endDate);
                if (endDate) {
                  endDateObj.setHours(23, 59, 59, 999); // Set to the last millisecond of the day
                }

                // If startDate equals endDate and is provided, filter for that specific date
                if (startDate === endDate && startDate !== "") {
                  if (
                    userVerificationDate.toDateString() !==
                    new Date(startDate).toDateString()
                  ) {
                    isInDateRange = false;
                  }
                } else {
                  // Check if the user verification date is within the date range
                  isInDateRange =
                    (startDate === "" ||
                      userVerificationDate >= new Date(startDate)) &&
                    (endDate === "" || userVerificationDate <= endDateObj); // Use the modified endDateObj here
                }

                return isInDateRange;
              })
              .map((user, index) => (
                <tr key={index} style={{ border: "1px solid #ddd" }}>
                                    <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.id_number}</td>

                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData.data.name}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data?.age || "Name not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data?.gender || "Gender not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data.district || "DOB not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data.state || "DOB not available"}</td>
                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.verifiedData?.data.polling_station || "DOB not available"}</td>

                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>{user.formattedDate || "DOB not available"}</td>

                  <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                    <button
                      onClick={() => handleDownloadPdf(user)}
                      title="Download PDF"
                      style={{
                        backgroundColor: "#4CAF50",
                        color: "white",
                        border: "none",
                        padding: "5px 10px",
                        borderRadius: "5px",
                        cursor: "pointer",
                      }}
                    >
                      <box-icon name='download'></box-icon>
                    </button>
                  </td>
                  {/* <td style={{ padding: "8px", border: "1px solid #ddd" }}>
                    <button
                    onClick={() => handleDelete(user.aadharNumber)}
                    title="Delete"
                    style={{
                        backgroundColor: "#f44336",
                        color: "white",
                        border: "none",
                        padding: "5px 10px",
                        borderRadius: "5px",
                        cursor: "pointer",
                    }}
                    >
                      <box-icon name="trash" type="solid"></box-icon>

                    </button>
                </td> */}
                </tr>
              ))}
          </tbody>
        </table>
      </div>
      {/* <button
        onClick={() => {
          localStorage.clear(); // Clears all data from localStorage
          alert("All local storage data has been cleared!");
        }}
        style={{
          padding: "10px 20px",
          backgroundColor: "#FF6347", // Color for the button
          color: "white",
          border: "none",
          borderRadius: "5px",
          cursor: "pointer",
        }}
      >
        Clear All Data
      </button> */}
    </>
  );
};

export default VoterTable;
